apiVersion: v1
kind: Service
metadata:
  name: app-rotten-potatoes-service
spec:
  selector:
    app: app-rotten-potatoes
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30000
  type: NodePort
